//! OS-keychain-backed database encryption key management (Security.md Section 5).

use rand::rngs::OsRng;
use rand::TryRngCore;

use super::SecretsError;

const SERVICE_NAME: &str = "com.healthproject.his";
const ACCOUNT_NAME: &str = "db-encryption-key";
const KEY_LEN_BYTES: usize = 32;

/// Abstraction over "get the persisted key, generating and storing one on first use" so
/// production code (`KeyringStore`, backed by the real OS credential store) and tests (an
/// in-memory fake, since headless CI has no Secret Service daemon — Security.md Section 5) can
/// share the same call site.
pub trait KeyStore {
    fn get_or_create(
        &self,
        service: &str,
        account: &str,
    ) -> Result<[u8; KEY_LEN_BYTES], SecretsError>;
}

pub struct KeyringStore;

impl KeyStore for KeyringStore {
    fn get_or_create(
        &self,
        service: &str,
        account: &str,
    ) -> Result<[u8; KEY_LEN_BYTES], SecretsError> {
        let entry = keyring::Entry::new(service, account)?;

        match entry.get_password() {
            Ok(existing_hex) => decode_key_hex(&existing_hex),
            Err(keyring::Error::NoEntry) => {
                let generated = generate_key()?;
                entry.set_password(&encode_hex(&generated))?;
                // Re-read the value that was actually persisted, rather than trusting the
                // freshly generated bytes, so a storage-layer round-trip bug is caught here.
                let stored_hex = entry.get_password()?;
                decode_key_hex(&stored_hex)
            }
            Err(other) => Err(SecretsError::Keyring(other)),
        }
    }
}

/// Public entry point used by `lib.rs::run()` at startup.
pub fn get_or_create_db_key() -> Result<[u8; KEY_LEN_BYTES], SecretsError> {
    KeyringStore.get_or_create(SERVICE_NAME, ACCOUNT_NAME)
}

fn generate_key() -> Result<[u8; KEY_LEN_BYTES], SecretsError> {
    let mut key = [0u8; KEY_LEN_BYTES];
    OsRng
        .try_fill_bytes(&mut key)
        .map_err(|error| SecretsError::InvalidHex(format!("CSPRNG failure: {error}")))?;
    Ok(key)
}

fn encode_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn decode_key_hex(hex: &str) -> Result<[u8; KEY_LEN_BYTES], SecretsError> {
    if hex.len() != KEY_LEN_BYTES * 2 {
        return Err(SecretsError::InvalidLength(hex.len() / 2));
    }

    let mut key = [0u8; KEY_LEN_BYTES];
    for (index, byte) in key.iter_mut().enumerate() {
        let start = index * 2;
        let pair = hex
            .get(start..start + 2)
            .ok_or_else(|| SecretsError::InvalidHex(hex.to_string()))?;
        *byte =
            u8::from_str_radix(pair, 16).map_err(|_| SecretsError::InvalidHex(hex.to_string()))?;
    }

    Ok(key)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use std::cell::RefCell;
    use std::collections::HashMap;

    use super::*;

    /// Test-only in-memory stand-in for the OS keychain (Security.md Section 5: "an explicit,
    /// clearly-named test-only key path, never reachable from production code"). Never used by
    /// `get_or_create_db_key()`.
    #[derive(Default)]
    struct InMemoryKeyStore {
        entries: RefCell<HashMap<(String, String), String>>,
    }

    impl KeyStore for InMemoryKeyStore {
        fn get_or_create(
            &self,
            service: &str,
            account: &str,
        ) -> Result<[u8; KEY_LEN_BYTES], SecretsError> {
            let key = (service.to_string(), account.to_string());
            if let Some(existing_hex) = self.entries.borrow().get(&key) {
                return decode_key_hex(existing_hex);
            }

            let generated = generate_key()?;
            self.entries
                .borrow_mut()
                .insert(key, encode_hex(&generated));
            Ok(generated)
        }
    }

    #[test]
    fn generates_and_persists_a_key_on_first_call() {
        let store = InMemoryKeyStore::default();
        let key = store.get_or_create(SERVICE_NAME, ACCOUNT_NAME).unwrap();
        assert_eq!(key.len(), KEY_LEN_BYTES);
    }

    #[test]
    fn returns_the_same_key_on_subsequent_calls() {
        let store = InMemoryKeyStore::default();
        let first = store.get_or_create(SERVICE_NAME, ACCOUNT_NAME).unwrap();
        let second = store.get_or_create(SERVICE_NAME, ACCOUNT_NAME).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn distinct_accounts_get_distinct_keys() {
        let store = InMemoryKeyStore::default();
        let key_a = store.get_or_create(SERVICE_NAME, "account-a").unwrap();
        let key_b = store.get_or_create(SERVICE_NAME, "account-b").unwrap();
        assert_ne!(key_a, key_b);
    }

    #[test]
    fn hex_round_trip_preserves_bytes() {
        let original = generate_key().unwrap();
        let encoded = encode_hex(&original);
        let decoded = decode_key_hex(&encoded).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn rejects_hex_of_the_wrong_length() {
        let result = decode_key_hex("abcd");
        assert!(result.is_err());
    }

    #[test]
    #[ignore = "requires a real OS keychain — run manually with `cargo test -- --ignored`, \
                never in headless CI (Security.md Section 5)"]
    fn keyring_store_round_trips_against_the_real_os_keychain() {
        let store = KeyringStore;
        let account = "phase1-manual-verification";
        let first = store.get_or_create(SERVICE_NAME, account).unwrap();
        let second = store.get_or_create(SERVICE_NAME, account).unwrap();
        assert_eq!(first, second);

        let entry = keyring::Entry::new(SERVICE_NAME, account).unwrap();
        entry.delete_credential().unwrap();
    }
}
