//! `notifications` domain model (Database.md Section 3.6). Generated by other services'
//! mutation commands (Inventory today; Operating Rooms in a later phase per `or_schedule`);
//! never written directly by the frontend.

use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Notification {
    pub id: i64,
    #[serde(rename = "type")]
    pub kind: String,
    pub target_role: Option<String>,
    pub message: String,
    pub related_entity_type: Option<String>,
    pub related_entity_id: Option<i64>,
    pub is_read: bool,
    pub created_at: String,
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn notification_serializes_field_names_as_camel_case() {
        let notification = Notification {
            id: 1,
            kind: "low_stock".to_string(),
            target_role: None,
            message: "Ibuprofen 400mg is at or below its reorder threshold".to_string(),
            related_entity_type: Some("inventory_item".to_string()),
            related_entity_id: Some(2),
            is_read: false,
            created_at: "2026-01-01T00:00:00Z".to_string(),
        };
        let json = serde_json::to_string(&notification).expect("serializes");
        assert!(json.contains("\"type\":\"low_stock\""));
        assert!(json.contains("\"targetRole\""));
        assert!(json.contains("\"relatedEntityType\""));
        assert!(json.contains("\"relatedEntityId\""));
        assert!(json.contains("\"isRead\":false"));
        assert!(json.contains("\"createdAt\""));
    }
}
