//! Notification orchestration (Database.md Section 3.6, IPC.md). Notifications are generated by
//! other modules' mutation commands, not created directly by the frontend.
//!
//! `check_inventory_alerts` is `pub(crate)` and called only from `commands/inventory_commands.rs`
//! right after each of the three Inventory mutation commands' own service call — it re-derives
//! nothing: it calls `inventory_service::list_low_stock_items`/`list_expiring_items`/
//! `list_due_maintenance_schedules` directly (Progress.md's Phase 10 Deviations require this).
//! Thresholds are fixed MVP constants computed with SQLite's own `date('now', '+N days')` rather
//! than a new date-library dependency (Rule 5.3 — no `chrono` crate exists in this codebase and
//! the arithmetic needed here is well under the 30-line bar that would justify adding one).
//!
//! Unlike every other service in this codebase, neither function here calls
//! `audit_service::record`. This is intentional, not an oversight: Audit.md states notifications
//! are not individually audited — only the triggering action is, and that action (e.g.
//! `inventory_item.create`, `inventory_transaction.create`) is already audited by
//! `inventory_service`.

use rusqlite::Connection;

use crate::db::DbError;
use crate::errors::AppError;
use crate::models::Notification;
use crate::repositories::notification_repository::{self, NewNotification};
use crate::services::inventory_service;
use crate::validation::notification_validation::{self, MarkNotificationReadInput};

const EXPIRATION_LOOKAHEAD_DAYS: i64 = 30;
const MAINTENANCE_LOOKAHEAD_DAYS: i64 = 7;

pub fn list_notifications(
    conn: &Connection,
    unread_only: bool,
) -> Result<Vec<Notification>, AppError> {
    Ok(notification_repository::list(conn, unread_only)?)
}

pub fn mark_read(
    conn: &Connection,
    input: &MarkNotificationReadInput,
) -> Result<Notification, AppError> {
    notification_validation::validate_mark_notification_read(input)?;

    notification_repository::mark_read(conn, input.id)?.ok_or(AppError::NotFound {
        entity: "notification".to_string(),
        id: input.id,
    })
}

/// Detects low-stock, near-expiration, and maintenance-due inventory conditions and inserts one
/// unread `Notification` row per newly-detected condition (skipping any that already has an
/// unread notification — Progress.md's dedup rule). Returns the notifications actually created,
/// so the caller can emit one `notifications:notification:created` event per row.
pub(crate) fn check_inventory_alerts(conn: &mut Connection) -> Result<Vec<Notification>, AppError> {
    let tx = conn.transaction().map_err(DbError::from)?;
    let mut created = Vec::new();

    for item in inventory_service::list_low_stock_items(&tx)? {
        let message = format!("{} is at or below its reorder threshold", item.name);
        if let Some(notification) =
            raise_if_new(&tx, "low_stock", "inventory_item", item.id, &message)?
        {
            created.push(notification);
        }
    }

    let expiration_cutoff = format!("date('now', '+{EXPIRATION_LOOKAHEAD_DAYS} days')");
    for item in
        inventory_service::list_expiring_items(&tx, &resolve_date(&tx, &expiration_cutoff)?)?
    {
        let message = format!("{} is approaching its expiration date", item.name);
        if let Some(notification) = raise_if_new(
            &tx,
            "medicine_expiration",
            "inventory_item",
            item.id,
            &message,
        )? {
            created.push(notification);
        }
    }

    let maintenance_cutoff = format!("date('now', '+{MAINTENANCE_LOOKAHEAD_DAYS} days')");
    for schedule in inventory_service::list_due_maintenance_schedules(
        &tx,
        &resolve_date(&tx, &maintenance_cutoff)?,
    )? {
        let message = "A maintenance schedule is coming due".to_string();
        if let Some(notification) = raise_if_new(
            &tx,
            "maintenance_due",
            "maintenance_schedule",
            schedule.id,
            &message,
        )? {
            created.push(notification);
        }
    }

    tx.commit().map_err(DbError::from)?;
    Ok(created)
}

fn raise_if_new(
    conn: &Connection,
    kind: &str,
    related_entity_type: &str,
    related_entity_id: i64,
    message: &str,
) -> Result<Option<Notification>, AppError> {
    if notification_repository::exists_unread(conn, kind, related_entity_type, related_entity_id)? {
        return Ok(None);
    }

    let id = notification_repository::insert(
        conn,
        &NewNotification {
            kind,
            target_role: None,
            message,
            related_entity_type: Some(related_entity_type),
            related_entity_id: Some(related_entity_id),
        },
    )?;
    let notification =
        notification_repository::find_by_id(conn, id)?.ok_or(AppError::NotFound {
            entity: "notification".to_string(),
            id,
        })?;
    Ok(Some(notification))
}

/// Evaluates a SQLite date expression (e.g. `date('now', '+30 days')`) into a `YYYY-MM-DD`
/// string, so the lookahead window is computed by SQLite itself rather than a new date library.
fn resolve_date(conn: &Connection, expression: &str) -> Result<String, AppError> {
    let value: String = conn
        .query_row(&format!("SELECT {expression}"), [], |row| row.get(0))
        .map_err(DbError::from)?;
    Ok(value)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use tempfile::tempdir;

    use super::*;
    use crate::db::{connection, migrator};
    use crate::validation::inventory_validation::{
        CreateInventoryItemInput, CreateInventoryTransactionInput, ScheduleMaintenanceInput,
    };

    const TEST_KEY: [u8; 32] = [71u8; 32];
    const ACTOR_USER_ID: i64 = 1;

    fn open_migrated(dir: &std::path::Path) -> Connection {
        let conn =
            connection::open(&dir.join("notification-service-test.sqlite"), &TEST_KEY).unwrap();
        migrator::run_migrations(&conn, migrator::embedded_migrations()).unwrap();
        conn.execute(
            "INSERT INTO users (full_name, username, password_hash, role) \
             VALUES ('Test Admin', 'test-admin', 'argon2id$dummy', 'admin')",
            [],
        )
        .unwrap();
        conn
    }

    fn create_item(conn: &mut Connection, reorder_threshold: i64) -> i64 {
        let category = inventory_service::create_category(
            conn,
            ACTOR_USER_ID,
            &crate::validation::inventory_validation::CreateInventoryCategoryInput {
                name: "Analgesics".to_string(),
                kind: "medicine".to_string(),
            },
        )
        .unwrap();
        inventory_service::create_item(
            conn,
            ACTOR_USER_ID,
            &CreateInventoryItemInput {
                category_id: category.id,
                name: "Ibuprofen 400mg".to_string(),
                unit: "box".to_string(),
                reorder_threshold,
                expiration_date: None,
                location: None,
            },
        )
        .unwrap()
        .id
    }

    #[test]
    fn check_inventory_alerts_raises_a_low_stock_notification() {
        let dir = tempdir().unwrap();
        let mut conn = open_migrated(dir.path());
        let item_id = create_item(&mut conn, 10);
        inventory_service::record_transaction(
            &mut conn,
            ACTOR_USER_ID,
            &CreateInventoryTransactionInput {
                item_id,
                quantity_delta: 5,
                reason: "restock".to_string(),
                encounter_id: None,
                treatment_id: None,
            },
        )
        .unwrap();

        let created = check_inventory_alerts(&mut conn).unwrap();

        assert_eq!(created.len(), 1);
        assert_eq!(created[0].kind, "low_stock");
        assert_eq!(created[0].related_entity_id, Some(item_id));
    }

    #[test]
    fn check_inventory_alerts_is_idempotent_for_an_unresolved_condition() {
        let dir = tempdir().unwrap();
        let mut conn = open_migrated(dir.path());
        let item_id = create_item(&mut conn, 10);
        inventory_service::record_transaction(
            &mut conn,
            ACTOR_USER_ID,
            &CreateInventoryTransactionInput {
                item_id,
                quantity_delta: 5,
                reason: "restock".to_string(),
                encounter_id: None,
                treatment_id: None,
            },
        )
        .unwrap();

        check_inventory_alerts(&mut conn).unwrap();
        let second_run = check_inventory_alerts(&mut conn).unwrap();

        assert!(second_run.is_empty());
        let all = notification_repository::list(&conn, false).unwrap();
        assert_eq!(all.len(), 1);
    }

    #[test]
    fn check_inventory_alerts_raises_a_maintenance_due_notification() {
        let dir = tempdir().unwrap();
        let mut conn = open_migrated(dir.path());
        let item_id = create_item(&mut conn, 0);
        inventory_service::schedule_maintenance(
            &mut conn,
            ACTOR_USER_ID,
            &ScheduleMaintenanceInput {
                inventory_item_id: item_id,
                scheduled_date: "2026-01-05".to_string(),
                notes: None,
            },
        )
        .unwrap();

        let created = check_inventory_alerts(&mut conn).unwrap();

        assert!(created.iter().any(|n| n.kind == "maintenance_due"));
    }

    #[test]
    fn mark_read_flips_the_flag() {
        let dir = tempdir().unwrap();
        let mut conn = open_migrated(dir.path());
        let item_id = create_item(&mut conn, 10);
        inventory_service::record_transaction(
            &mut conn,
            ACTOR_USER_ID,
            &CreateInventoryTransactionInput {
                item_id,
                quantity_delta: 5,
                reason: "restock".to_string(),
                encounter_id: None,
                treatment_id: None,
            },
        )
        .unwrap();
        let created = check_inventory_alerts(&mut conn).unwrap();

        let updated = mark_read(&conn, &MarkNotificationReadInput { id: created[0].id }).unwrap();

        assert!(updated.is_read);
    }

    #[test]
    fn mark_read_on_a_nonexistent_id_returns_not_found() {
        let dir = tempdir().unwrap();
        let conn = open_migrated(dir.path());

        let result = mark_read(&conn, &MarkNotificationReadInput { id: 999 });

        assert!(matches!(result, Err(AppError::NotFound { .. })));
    }
}
